<a href="https://colab.research.google.com/github/bsravani6303/AI-Based-cybersecurity-threat-prediction-agent/blob/main/Python_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Python task**

prompt: Create a class 'Student' to calculate grade


In [ ]:
class Student:

    def __init__(self, name, marks):
        self.__name = name
        self.__marks = marks # private variable

    def get_name(self):
        return self.__name

    def calculate_grade(self):
        avg = sum(self.__marks) / len(self.__marks)
        if avg >= 90:
            return 'A'
        elif avg >= 75:
            return 'B'
        elif avg >= 60:
            return 'C'
        else:
            return 'D'
s1 = Student("Alice", [85, 90, 88])
print(f"{s1.get_name()} got grade {s1.calculate_grade()}")

Alice got grade B


 Using NumPy – Create a 2D matrix and perform matrix operations

In [ ]:
import numpy as np

A = np.array([[2, 4], [6, 8]])
B = np.array([[1, 3], [5, 7]])

print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("\nA + B =\n", A + B)
print("\nA × B (matrix multiplication) =\n", np.dot(A, B))
print("\nTranspose of A =\n", A.T)

Matrix A:
 [[2 4]
 [6 8]]
Matrix B:
 [[1 3]
 [5 7]]

A + B =
 [[ 3  7]
 [11 15]]

A × B (matrix multiplication) =
 [[22 34]
 [46 74]]

Transpose of A =
 [[2 6]
 [4 8]]


Prompt: Using Pandas – Filter, sort, and analyze data from a DataFrame

In [ ]:
import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [20, 22, 23, 21, 24],
    'Score': [85, 72, 90, 60, 88]
}

df = pd.DataFrame(data)
print("Original Data:\n", df)


filtered = df[df['Score'] > 80]
print("\nStudents with Score > 80:\n", filtered)


sorted_df = df.sort_values(by='Score', ascending=False)
print("\nSorted by Score:\n", sorted_df)


print("\nAverage Score:", df['Score'].mean())

Original Data:
       Name  Age  Score
0    Alice   20     85
1      Bob   22     72
2  Charlie   23     90
3    David   21     60
4      Eva   24     88

Students with Score > 80:
       Name  Age  Score
0    Alice   20     85
2  Charlie   23     90
4      Eva   24     88

Sorted by Score:
       Name  Age  Score
2  Charlie   23     90
4      Eva   24     88
0    Alice   20     85
1      Bob   22     72
3    David   21     60

Average Score: 79.0


Prompt: Create a decorator to measure execution time of a function

In [ ]:
import time

def timer(func):
    def wrapper(*args, **kwargs):
        start = time.time()
        result = func(*args, **kwargs)
        end = time.time()
        print(f"⏱️ Execution time: {end - start:.4f} seconds")
        return result
    return wrapper

@timer
def compute_sum(n):
    return sum(range(n))

print("Sum:", compute_sum(10_000_000))

⏱️ Execution time: 0.1198 seconds
Sum: 49999995000000



Prompt: Fetch live data from an API (e.g., JSON placeholder) and process it

In [ ]:
import requests

url = "https://jsonplaceholder.typicode.com/posts"
response = requests.get(url)
posts = response.json()

print(f"Total Posts Fetched: {len(posts)}")

# Print first 3 titles
for p in posts[:3]:
    print("-", p["title"])

Total Posts Fetched: 100
- sunt aut facere repellat provident occaecati excepturi optio reprehenderit
- qui est esse
- ea molestias quasi exercitationem repellat qui ipsa sit aut



Prompt: Use List Comprehension and Lambda to clean & transform data

In [ ]:

nums = [1, 2, 3, 4, 5, 6, 7, 8, 9]
squares = [x**2 for x in nums if x % 2 == 0]
print("Even squares:", squares)
doubles = list(map(lambda x: x * 2, nums))
print("Doubled values:", doubles)

Even squares: [4, 16, 36, 64]
Doubled values: [2, 4, 6, 8, 10, 12, 14, 16, 18]


Prompt:Exception Handling – Handle multiple errors in a single block

In [ ]:
try:
    x = int(input("Enter a number: "))
    print(10 / x)
except ValueError:
    print("❌ Invalid input! Please enter a number.")
except ZeroDivisionError:
    print("❌ Cannot divide by zero!")
finally:
    print("✅ Task complete.")

Enter a number: 465
0.021505376344086023
✅ Task complete.
